Menu
Jeeffsantoos/AP2_PRATICA_PYTHON pull request #9
Opened 2023-05-19 21:28 UTC by VictorLopesz

Código com um menu interativo que permite ao usuário realizar operações de manipulação de arquivos, como excluir, ler, adicionar e editar arquivos.

2023-05-19 21:38 UTC, dgsmiley18 requested changes
Menu foi feita de forma incorreta, invés de usar os arquivos já criados para fazer o crud no banco de dados, agora foi criado outras funções para criação de arquivo de texto, por favor refaça com que use os arquivos já existentes.

2023-05-20 15:55 UTC, Jeeffsantoos requested changes
Código está manipulando arquivos de texto.

2023-05-20 15:59 UTC, Jeeffsantoos requested changes
A condicional está ok, faremos os ajustes necessários!
Porém, você está manipulando banco de dados com a lib do mysql.

Não é necessário recriar as funções do CRUD, nós já fizemos. 

Sugiro que de uma olhada na lib nativa "SQLite" do python. Nós já fizemos as operações de CRUD.

2023-05-20 18:50 UTC, Jeeffsantoos requested changes
Abri no codespace para testar e verifiquei que você está chamando funções que não foram criadas.

2023-05-21 00:05 UTC, dgsmiley18 requested changes
Está chegando perto, mas ainda tem alguns erros a serem resolvidos.

2023-05-21 00:05 UTC, dgsmiley18 commented on main.py
> -if __name__ == '__main__':
Deletando essa parte você fez com que o banco de dados não fosse criado, e esqueceu de colocar o menu() para iniciar, fazendo que o código inteiro não inicie, por favor coloque essa linha novamente porém apenas com o menu()

2023-05-21 00:05 UTC, dgsmiley18 commented on main.py
>  from atualizarDadosVenda import atualizarDataVenda, atualizarIdCliente, atualizarIdVendidaVenda
Aparentemente o "atualizarIdVendidaVenda" está com erro de digitação, por favor resolver nessa linha e no arquivo
"atualizarDadosVenda.py"

2023-05-21 00:05 UTC, dgsmiley18 commented on main.py
> +           adicionarCliente()
Todas as funções do arquivo "adicionarCampo.py" precisam de argumentos, por favor olhe o arquivo e cheque quais argumentos eles precisam, depois volte para o "main.py" e coloque os argumentos necessários.

2023-05-21 00:05 UTC, dgsmiley18 commented on .idea/vcs.xml
Você enviou arquivos não relacionados com o projeto, por favor deletar eles e não enviar novamente (Pycharm costuma fazer isso)

2023-05-22 17:59 UTC, dgsmiley18 approved these changes
Todos os problemas foram resolvidos e funcionando conforme o planejado, aceitando esse pull request resolvera a issue #3

2023-05-22 18:01 UTC, VictorLopesz commented
Problema da query resolvido no deletarCampo e menu criado com sucesso

2023-05-22 20:35 UTC, Jeeffsantoos approved these changes
Tudo ok!

2023-05-22 20:36 UTC, merged